"""add_article_type_to_articles

Revision ID: fbcc9c9a78e6
Revises: db429e5d049c
Create Date: 2026-05-05 08:23:55.552519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcc9c9a78e6'
down_revision: Union[str, None] = 'db429e5d049c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE articles ADD COLUMN article_type INT NOT NULL AFTER id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_type')
    # ### end Alembic commands ###
